remote_theme: pages-themes/modernist@v0.2.0
# theme: jekyll-theme-modernist
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-remote-theme, jekyll-sitemap]
url: "https://infocookie.github.io"
permalink: /:title/
plugins: 
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
title: [InfoCookie]
description: [쿠키처럼 먹기 쉽게 요약된 정보들]



compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: true
  startings: [html, head, body]
